/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author anhha
 */
public class AddDrugsFrm extends javax.swing.JFrame {

    /**
     * Creates new form AddDrugsFrm
     */
    public AddDrugsFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_title = new javax.swing.JLabel();
        jLabel_drugsid = new javax.swing.JLabel();
        jLabel_drugsname = new javax.swing.JLabel();
        jLabel_group = new javax.swing.JLabel();
        jLabel_type = new javax.swing.JLabel();
        jLabel_ingredient = new javax.swing.JLabel();
        jLabel_supplierid = new javax.swing.JLabel();
        jLabel_dayreception = new javax.swing.JLabel();
        jLabel_expirydate = new javax.swing.JLabel();
        jLabel_amount = new javax.swing.JLabel();
        jLabel_price = new javax.swing.JLabel();
        jTextField_drugsid = new javax.swing.JTextField();
        jTextField_drugsname = new javax.swing.JTextField();
        jTextField_group = new javax.swing.JTextField();
        jTextField_type = new javax.swing.JTextField();
        jTextField_ingredient = new javax.swing.JTextField();
        jTextField_supplierid = new javax.swing.JTextField();
        jTextField_dayreception = new javax.swing.JTextField();
        jTextField_expirydate = new javax.swing.JTextField();
        jTextField_amount = new javax.swing.JTextField();
        jTextField_price = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_title.setText("Các thành phần của Thuốc");

        jLabel_drugsid.setText("Mã thuốc");

        jLabel_drugsname.setText("Tên thuốc");

        jLabel_group.setText("Nhóm");

        jLabel_type.setText("Loại");

        jLabel_ingredient.setText("thành phần");

        jLabel_supplierid.setText("Mã nhà cung cấp");

        jLabel_dayreception.setText("Ngày tiếp nhận");

        jLabel_expirydate.setText("Hạn sử dụng");

        jLabel_amount.setText("SL_DVT");

        jLabel_price.setText("Giá bán");

        jTextField_drugsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_drugsidActionPerformed(evt);
            }
        });

        jButton_add.setText("Thêm");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_reset.setText("Reset");

        jButton_cancel.setText("Huỷ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton_add)
                        .addGap(50, 50, 50)
                        .addComponent(jButton_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_cancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_ingredient)
                                .addGap(66, 66, 66)
                                .addComponent(jTextField_ingredient))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_supplierid)
                                .addGap(40, 40, 40)
                                .addComponent(jTextField_supplierid))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_dayreception)
                                .addGap(48, 48, 48)
                                .addComponent(jTextField_dayreception))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_expirydate)
                                .addGap(60, 60, 60)
                                .addComponent(jTextField_expirydate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_amount)
                                .addGap(85, 85, 85)
                                .addComponent(jTextField_amount))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_price)
                                .addGap(85, 85, 85)
                                .addComponent(jTextField_price))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_drugsid)
                                    .addComponent(jLabel_drugsname))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_drugsname, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_drugsid, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_group)
                                    .addComponent(jTextField_type)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel_title)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_drugsid)
                    .addComponent(jTextField_drugsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_drugsname)
                    .addComponent(jTextField_drugsname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_group)
                    .addComponent(jTextField_group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_type))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ingredient)
                    .addComponent(jTextField_ingredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_supplierid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_supplierid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dayreception)
                    .addComponent(jTextField_dayreception, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_expirydate)
                    .addComponent(jTextField_expirydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_amount))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_price)
                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add)
                    .addComponent(jButton_reset)
                    .addComponent(jButton_cancel))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_drugsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_drugsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_drugsidActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDrugsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDrugsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDrugsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDrugsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDrugsFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JLabel jLabel_amount;
    private javax.swing.JLabel jLabel_dayreception;
    private javax.swing.JLabel jLabel_drugsid;
    private javax.swing.JLabel jLabel_drugsname;
    private javax.swing.JLabel jLabel_expirydate;
    private javax.swing.JLabel jLabel_group;
    private javax.swing.JLabel jLabel_ingredient;
    private javax.swing.JLabel jLabel_price;
    private javax.swing.JLabel jLabel_supplierid;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JLabel jLabel_type;
    private javax.swing.JTextField jTextField_amount;
    private javax.swing.JTextField jTextField_dayreception;
    private javax.swing.JTextField jTextField_drugsid;
    private javax.swing.JTextField jTextField_drugsname;
    private javax.swing.JTextField jTextField_expirydate;
    private javax.swing.JTextField jTextField_group;
    private javax.swing.JTextField jTextField_ingredient;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextField jTextField_supplierid;
    private javax.swing.JTextField jTextField_type;
    // End of variables declaration//GEN-END:variables
}
