/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author anhha
 */
public class AddGuestFrm extends javax.swing.JFrame {

    /**
     * Creates new form AddGuestFrm
     */
    public AddGuestFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_title = new javax.swing.JLabel();
        jLabel_goestid = new javax.swing.JLabel();
        jLabel_guestname = new javax.swing.JLabel();
        jLabel_guestsex = new javax.swing.JLabel();
        jLabel_guestaddress = new javax.swing.JLabel();
        jTextField_guestid = new javax.swing.JTextField();
        jTextField_guestname = new javax.swing.JTextField();
        jTextField_guestsex = new javax.swing.JTextField();
        jTextField_guestaddress = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_title.setText("Khách Hàng");

        jLabel_goestid.setText("Mã khách hàng:");

        jLabel_guestname.setText("Họ tên:");

        jLabel_guestsex.setText("Giới tính:");

        jLabel_guestaddress.setText("Địa chỉ:");

        jTextField_guestname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_guestnameActionPerformed(evt);
            }
        });

        jTextField_guestsex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_guestsexActionPerformed(evt);
            }
        });

        jButton_add.setText("Thêm");

        jButton_reset.setText("Reset");

        jButton_cancel.setText("Huỷ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_guestname)
                            .addComponent(jLabel_goestid)
                            .addComponent(jLabel_guestsex)
                            .addComponent(jLabel_guestaddress))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_guestid)
                            .addComponent(jTextField_guestname)
                            .addComponent(jTextField_guestsex)
                            .addComponent(jTextField_guestaddress)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel_title)
                                .addGap(0, 113, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton_add)
                        .addGap(62, 62, 62)
                        .addComponent(jButton_reset)
                        .addGap(49, 49, 49)
                        .addComponent(jButton_cancel)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_goestid)
                    .addComponent(jTextField_guestid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_guestname)
                    .addComponent(jTextField_guestname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_guestsex)
                    .addComponent(jTextField_guestsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_guestaddress)
                    .addComponent(jTextField_guestaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add)
                    .addComponent(jButton_reset)
                    .addComponent(jButton_cancel))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_guestsexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_guestsexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_guestsexActionPerformed

    private void jTextField_guestnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_guestnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_guestnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGuestFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGuestFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGuestFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGuestFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGuestFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JLabel jLabel_goestid;
    private javax.swing.JLabel jLabel_guestaddress;
    private javax.swing.JLabel jLabel_guestname;
    private javax.swing.JLabel jLabel_guestsex;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JTextField jTextField_guestaddress;
    private javax.swing.JTextField jTextField_guestid;
    private javax.swing.JTextField jTextField_guestname;
    private javax.swing.JTextField jTextField_guestsex;
    // End of variables declaration//GEN-END:variables
}
