/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author anhha
 */
public class AddPharmacistFrm extends javax.swing.JFrame {

    /**
     * Creates new form AddStaffFrm
     */
    public AddPharmacistFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jLabel_titile = new javax.swing.JLabel();
        jLabel_staffid = new javax.swing.JLabel();
        jLabel_staffname = new javax.swing.JLabel();
        jLabel_dateofbirth = new javax.swing.JLabel();
        jLabel_sex = new javax.swing.JLabel();
        jLabel_address = new javax.swing.JLabel();
        jLabel_phonenumber = new javax.swing.JLabel();
        jLabel_shift = new javax.swing.JLabel();
        txtPharmacistID = new javax.swing.JTextField();
        txtPharmacistName = new javax.swing.JTextField();
        txtPharmacistDOB = new javax.swing.JTextField();
        txtPharmacistSex = new javax.swing.JTextField();
        txtPharmacistAddress = new javax.swing.JTextField();
        txtPharmacistPhone = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmbShift = new javax.swing.JComboBox<>();

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_titile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_titile.setText("Nhân Viên");

        jLabel_staffid.setText("Mã nhân viên: ");

        jLabel_staffname.setText("Họ tên:");

        jLabel_dateofbirth.setText("Ngày sinh:");

        jLabel_sex.setText("Giới tính:");

        jLabel_address.setText("Địa chỉ:");

        jLabel_phonenumber.setText("Số điện thoại:");

        jLabel_shift.setText("Ca làm:");

        txtPharmacistID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPharmacistIDActionPerformed(evt);
            }
        });

        txtPharmacistAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPharmacistAddressActionPerformed(evt);
            }
        });

        txtPharmacistPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPharmacistPhoneActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");

        btnReset.setText("Reset");

        btnCancel.setText("Huỷ");

        cmbShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_shift)
                    .addComponent(jLabel_phonenumber)
                    .addComponent(jLabel_address)
                    .addComponent(jLabel_sex)
                    .addComponent(jLabel_staffid)
                    .addComponent(jLabel_staffname)
                    .addComponent(jLabel_dateofbirth)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(67, 67, 67)
                        .addComponent(btnCancel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbShift, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_titile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPharmacistID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addComponent(txtPharmacistName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPharmacistDOB, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPharmacistSex, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPharmacistAddress, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPharmacistPhone, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel_titile)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_staffid)
                    .addComponent(txtPharmacistID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_staffname)
                    .addComponent(txtPharmacistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_dateofbirth)
                    .addComponent(txtPharmacistDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_sex)
                    .addComponent(txtPharmacistSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_address)
                    .addComponent(txtPharmacistAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_phonenumber)
                    .addComponent(txtPharmacistPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_shift)
                    .addComponent(cmbShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnReset)
                    .addComponent(btnCancel))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPharmacistIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPharmacistIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPharmacistIDActionPerformed

    private void txtPharmacistAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPharmacistAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPharmacistAddressActionPerformed

    private void txtPharmacistPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPharmacistPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPharmacistPhoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbShift;
    private javax.swing.JLabel jLabel_address;
    private javax.swing.JLabel jLabel_dateofbirth;
    private javax.swing.JLabel jLabel_phonenumber;
    private javax.swing.JLabel jLabel_sex;
    private javax.swing.JLabel jLabel_shift;
    private javax.swing.JLabel jLabel_staffid;
    private javax.swing.JLabel jLabel_staffname;
    private javax.swing.JLabel jLabel_titile;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtPharmacistAddress;
    private javax.swing.JTextField txtPharmacistDOB;
    private javax.swing.JTextField txtPharmacistID;
    private javax.swing.JTextField txtPharmacistName;
    private javax.swing.JTextField txtPharmacistPhone;
    private javax.swing.JTextField txtPharmacistSex;
    // End of variables declaration//GEN-END:variables
}
