/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;
import model.Drug;

/**
 *
 * @author THAONGAN
 */
public class EditDrugFrm extends javax.swing.JFrame {
    private DrugPanel drugPanel;
    
    /**
     * Creates new form AddDrug
     */
    public EditDrugFrm(JPanel parent) {
        initComponents();
        this.setLocationRelativeTo(null);
        drugPanel = (DrugPanel) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDrugID = new javax.swing.JLabel();
        jLabel_drugsid = new javax.swing.JLabel();
        jLabel_drugsname = new javax.swing.JLabel();
        jLabel_group = new javax.swing.JLabel();
        jLabel_type = new javax.swing.JLabel();
        jLabel_ingredient = new javax.swing.JLabel();
        jLabel_expirydate = new javax.swing.JLabel();
        jLabel_amount = new javax.swing.JLabel();
        jLabel_supplierid = new javax.swing.JLabel();
        jLabel_dayreception = new javax.swing.JLabel();
        txtDrugId = new javax.swing.JTextField();
        txtDrugName = new javax.swing.JTextField();
        txtDrugGroup = new javax.swing.JTextField();
        txtDrugIngr = new javax.swing.JTextField();
        txtExpiredDate = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        txtSupplierID = new javax.swing.JTextField();
        txtDateImport = new javax.swing.JTextField();
        cmbDrugType = new javax.swing.JComboBox<>();
        btnEditDrug = new javax.swing.JButton();
        btnCancelDrug = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sửa Thuốc");
        setResizable(false);

        txtDrugID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDrugID.setText("Thông tin thuốc");

        jLabel_drugsid.setText("Mã thuốc");

        jLabel_drugsname.setText("Tên thuốc");

        jLabel_group.setText("Nhóm");

        jLabel_type.setText("Loại");

        jLabel_ingredient.setText("Thành phần");

        jLabel_expirydate.setText("Hạn sử dụng");

        jLabel_amount.setText("Đơn vị tính");

        jLabel_supplierid.setText("Mã nhà cung cấp");

        jLabel_dayreception.setText("Ngày tiếp nhận");

        txtDrugId.setEditable(false);

        cmbDrugType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thuốc kê đơn", "Thuốc không kê đơn", "Thực phẩm chức năng" }));

        btnEditDrug.setText("Sửa");
        btnEditDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDrugActionPerformed(evt);
            }
        });

        btnCancelDrug.setText("Huỷ");
        btnCancelDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelDrugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_drugsid)
                    .addComponent(jLabel_drugsname)
                    .addComponent(jLabel_group)
                    .addComponent(jLabel_type, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ingredient)
                    .addComponent(jLabel_expirydate)
                    .addComponent(jLabel_amount)
                    .addComponent(jLabel_supplierid)
                    .addComponent(jLabel_dayreception))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDrugId)
                    .addComponent(txtDrugName)
                    .addComponent(txtDrugGroup)
                    .addComponent(txtDrugIngr)
                    .addComponent(txtExpiredDate)
                    .addComponent(txtUnit)
                    .addComponent(txtSupplierID)
                    .addComponent(txtDateImport)
                    .addComponent(cmbDrugType, 0, 202, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(txtDrugID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnEditDrug)
                        .addGap(83, 83, 83)
                        .addComponent(btnCancelDrug)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtDrugID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_drugsid)
                    .addComponent(txtDrugId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_drugsname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_group)
                    .addComponent(txtDrugGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_type)
                    .addComponent(cmbDrugType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ingredient)
                    .addComponent(txtDrugIngr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_expirydate)
                    .addComponent(txtExpiredDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_amount)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_supplierid)
                    .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_dayreception)
                    .addComponent(txtDateImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditDrug)
                    .addComponent(btnCancelDrug))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDrugActionPerformed
        String sMathuoc = "", sTenthuoc = "", sPhannhom = "", sPhanloai = "", sThanhphan = "", sMancc = "";
        String sHansudung = "", sNgaytiepnhan = "";
        String sDVT = "";
        
        sMathuoc = txtDrugId.getText();
        sTenthuoc = txtDrugName.getText();
        sPhannhom = txtDrugGroup.getText();
        sPhanloai = cmbDrugType.getItemAt(cmbDrugType.getSelectedIndex());
        sThanhphan = txtDrugIngr.getText();
        sMancc = txtSupplierID.getText();
        sHansudung = txtExpiredDate.getText();
        sNgaytiepnhan = txtDateImport.getText();
        sDVT = txtUnit.getText();
        
        
        
        Drug drug = new Drug(sMathuoc, sTenthuoc,sPhannhom,  sPhanloai, sThanhphan, sHansudung, sDVT, sMancc, sNgaytiepnhan);
        drugPanel.EditDrug(drug);
        this.dispose();
                // TODO add your handling code here:
    }//GEN-LAST:event_btnEditDrugActionPerformed

    private void btnCancelDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelDrugActionPerformed
            this.dispose();
                // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelDrugActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelDrug;
    private javax.swing.JButton btnEditDrug;
    private javax.swing.JComboBox<String> cmbDrugType;
    private javax.swing.JLabel jLabel_amount;
    private javax.swing.JLabel jLabel_dayreception;
    private javax.swing.JLabel jLabel_drugsid;
    private javax.swing.JLabel jLabel_drugsname;
    private javax.swing.JLabel jLabel_expirydate;
    private javax.swing.JLabel jLabel_group;
    private javax.swing.JLabel jLabel_ingredient;
    private javax.swing.JLabel jLabel_supplierid;
    private javax.swing.JLabel jLabel_type;
    private javax.swing.JTextField txtDateImport;
    private javax.swing.JTextField txtDrugGroup;
    private javax.swing.JLabel txtDrugID;
    private javax.swing.JTextField txtDrugId;
    private javax.swing.JTextField txtDrugIngr;
    private javax.swing.JTextField txtDrugName;
    private javax.swing.JTextField txtExpiredDate;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables

    public void setEditData(Drug d) {
        txtDrugId.setText(d.getsMathuoc());
        txtDrugId.setEditable(false);
        txtDrugName.setText(d.getsTenthuoc());
        txtDrugGroup.setText(d.getsPhannhom());
        cmbDrugType.setSelectedItem(d.getsPhanloai());
        txtDrugIngr.setText(d.getsThanhphan());
        txtExpiredDate.setText(d.getsHansudung());
        txtUnit.setText(d.getsDVT());
        txtSupplierID.setText(d.getsMancc());
        txtDateImport.setText(d.getsNgaytiepnhan());
        
    }
}
